apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mijn-host-webhook.fullname" . }}:secret-reader
  namespace: {{ .Values.certManager.namespace }}
  labels:
    {{- include "mijn-host-webhook.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ .Values.secretName | quote }}]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mijn-host-webhook.fullname" . }}:secret-reader
  namespace: {{ .Values.certManager.namespace }}
  labels:
    {{- include "mijn-host-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mijn-host-webhook.fullname" . }}:secret-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "mijn-host-webhook.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mijn-host-webhook.fullname" . }}:domain-solver
  labels:
    {{- include "mijn-host-webhook.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - "*"
    verbs:
      - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mijn-host-webhook.fullname" . }}:domain-solver
  labels:
    {{- include "mijn-host-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mijn-host-webhook.fullname" . }}:domain-solver
subjects:
  - kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
