apiVersion: v1
kind: Service
metadata:
  name: {{ include "mijn-host-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mijn-host-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "mijn-host-webhook.selectorLabels" . | nindent 4 }}
