groupName: acme.vanefferenonline.nl

image:
  repository: ghcr.io/sircuri/cert-manager-webhook-mijn-host
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

secretName: mijn-host-api-key

replicaCount: 1

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
